import { ITheme } from '~/interfaces';
import { BLUE_500 } from './colors';

export const lightTheme: ITheme = {
  'titlebar.backgroundColor': '#E0E0E0',
  'addressbar.backgroundColor': '#fff',
  'toolbar.backgroundColor': '#f6f5f5',
  'toolbar.bottomLine.backgroundColor': 'rgba(0, 0, 0, 0.12)',
  'toolbar.lightForeground': false,
  'toolbar.separator.color': 'rgba(0, 0, 0, 0.12)',
  'tab.selected.textColor': '#000',
  'tab.textColor': `rgba(0, 0, 0, 0.7)`,
  'control.backgroundColor': 'rgba(0, 0, 0, 0.08)',
  'control.hover.backgroundColor': 'rgba(0, 0, 0, 0.1)',
  'control.valueColor': '#000',
  'control.lightIcon': false,
  'switch.backgroundColor': 'rgba(0, 0, 0, 0.16)',
  'dialog.backgroundColor': '#fff',
  'dialog.separator.color': 'rgba(0, 0, 0, 0.12)',
  'dialog.textColor': '#000',
  'dialog.lightForeground': false,
  'searchBox.subHeading.backgroundColor': '#fafafa',
  'searchBox.subHeading.textColor': 'rgba(0, 0, 0, 0.54)',
  'searchBox.input.backgroundColor': '#fff',
  'searchBox.input.lightForeground': false,
  'searchBox.input.textColor': '#000',
  'searchBox.suggestions.backgroundColor': '#fff',
  'searchBox.suggestions.lightForeground': false,
  'searchBox.suggestions.textColor': '#000',
  'pages.backgroundColor': '#fff',
  'pages.lightForeground': false,
  'pages.textColor': '#000',
  'dropdown.backgroundColor': '#fff',
  'dropdown.backgroundColor.translucent': 'rgba(255, 255, 255, 0.7)',
  'dropdown.separator.color': 'rgba(0, 0, 0, 0.12)',
  'pages.navigationDrawer1.backgroundColor': '#f5f5f5',
  'pages.navigationDrawer2.backgroundColor': '#fafafa',

  accentColor: BLUE_500,
  backgroundColor: '#fff',
};

export const darkTheme: ITheme = {
  'titlebar.backgroundColor': '#1c1c1c',
  'addressbar.backgroundColor': 'rgba(0, 0, 0, 0.18)',
  'toolbar.backgroundColor': '#2e2e2e',
  'toolbar.bottomLine.backgroundColor': 'rgba(255, 255, 255, 0.08)',
  'toolbar.lightForeground': true,
  'toolbar.separator.color': 'rgba(255, 255, 255, 0.12)',
  'tab.selected.textColor': '#fff',
  'tab.textColor': 'rgba(255, 255, 255, 0.54)',
  'control.backgroundColor': 'rgba(255, 255, 255, 0.1)',
  'control.hover.backgroundColor': 'rgba(255, 255, 255, 0.12)',
  'control.valueColor': '#fff',
  'control.lightIcon': true,
  'switch.backgroundColor': 'rgba(255, 255, 255, 0.24)',
  'dialog.backgroundColor': '#383838',
  'dialog.separator.color': 'rgba(255, 255, 255, 0.12)',
  'dialog.textColor': '#fff',
  'dialog.lightForeground': true,
  'searchBox.subHeading.backgroundColor': 'rgba(0, 0, 0, 0.12)',
  'searchBox.subHeading.textColor': 'rgba(255, 255, 255, 0.54)',
  'searchBox.input.backgroundColor': '#424242',
  'searchBox.input.lightForeground': true,
  'searchBox.input.textColor': '#fff',
  'searchBox.suggestions.backgroundColor': '#424242',
  'searchBox.suggestions.lightForeground': true,
  'searchBox.suggestions.textColor': '#fff',
  'pages.backgroundColor': '#1c1c1c',
  'pages.lightForeground': true,
  'pages.textColor': '#fff',
  'dropdown.backgroundColor': 'rgb(66, 66, 66)',
  'dropdown.backgroundColor.translucent': 'rgb(60, 60, 60, 0.6)',
  'dropdown.separator.color': 'rgba(255, 255, 255, 0.12)',
  'pages.navigationDrawer1.backgroundColor': 'rgba(255, 255, 255, 0.1)',
  'pages.navigationDrawer2.backgroundColor': 'rgba(255, 255, 255, 0.05)',

  backgroundColor: '#1c1c1c',
  accentColor: BLUE_500,
};
