namespace tabsPrivate {};

interface Functions {
  static void getNavigationState(long tabId);

  static void stop(long tabId);
};

interface Events {
  static void onFaviconUpdated(long tabId, DOMString faviconUrl);
};
