export const opacity = {
  light: {
    primaryText: 0.87,
    secondaryText: 0.54,
    disabledText: 0.38,
    activeIcon: 1,
    inactiveIcon: 0.54,
    disabledIcon: 0.38,
    dividers: 0.12,
    activeControl: 1,
    inactiveControl: 0.54,
    disabledControl: 0.26,
  },
  dark: {
    primaryText: 1,
    secondaryText: 0.7,
    disabledText: 0.3,
    activeIcon: 1,
    inactiveIcon: 0.54,
    disabledIcon: 0.38,
    dividers: 0.2,
    activeControl: 1,
    inactiveControl: 0.7,
    disabledControl: 0.3,
  },
};
